# Site settings
title: Jonpersson.dk
email: jon.persson.88@gmail.com
description: # JonPerssons test website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jonpersson.dk" # the base hostname & protocol for your site
twitter_username: JonPersson
github_username:  Jon-Persson

# Build settings
markdown: kramdown
highlighter: rouge
github: [Repository metadata]